web:
  build: .
  volumes:
    - ./www:/var/www/site
  links:
   - mysql
  ports:
   - 8080:80
  stdin_open: true
  tty: true

phpmyadmin:
  image: corbinu/docker-phpmyadmin
  links:
    - mysql
  ports:
   - 8081:80
  environment:
    MYSQL_USERNAME: root
    MYSQL_ROOT_PASSWORD: 123

mysql:
  image: mysql:5.7
  environment:
    - MYSQL_ROOT_PASSWORD=123
    - MYSQL_DATABASE=wordpress